In [ ]:
# standard deviation
import numpy as np
np.sqrt(np.var(msleep['sleep_total'], ddof=1))
np.std(msleep['sleep_total'], ddof=1)

# mean absolute deviation
dists = msleep['sleep_total'] - mean(msleep$sleep_total)
np.mean(np.abs(dists))

# quantiles
np.quantile(msleep['sleep_total'], 0.5)
np.quantile(msleep['sleep_total'], np.linspace(0, 1, 5)) # linspace(start, stop, num)
np.quantile(msleep['sleep_total'], 0.75) - np.quantile(msleep['sleep_total'], 0.25)

from scipy.stats import iqr
iqr(msleep['sleep_total'])

# finding outliers
from scipy.stats import iqr
iqr = iqr(msleep['bodywt'])
lower_thresold = np.quantile(msleep['bodywt'], 0.25) - 1.5 * iqr
upper_thresold = np.quantile(msleep['bodywt'], 0.75) + 1.5 * iqr
# msleep[(msleep['bodywt'] < lower_threshold) | (msleep['bodywt'] > upper_threshold)]
msleep['bodywt'].describe()

In [ ]:
print(sales_counts)
sales_counts.sample()

np.random.seed(10)


In [5]:
# Uniform distribution in Python
from scipy.stats import uniform
uniform.cdf(7, 0, 12)
uniform.rvs(0,5,10)

array([4.93189631, 0.69602187, 4.87006423, 2.39259247, 4.07645843,
       3.34936485, 4.88882864, 1.81086929, 1.50120324, 1.5086743 ])

In [19]:
# single flip
from scipy.stats import binom
binom.rvs(1,0.5,size=5)
binom.rvs(5,0.5,size=1) # number of heads

# Simulate 52 weeks of 3 deals
deals = binom.rvs(3, 0.3, size=52)

# biased coin
binom.rvs(3, 0.25, size=10)

# binomial distribution
binom.pmf(7, 10, 0.5)   #(num_heads, num_trials, prob_of_heads)
binom.cdf(7, 10, 0.5)   #p(heads <= 7)


0.9453125

In [9]:
# normal distribution
from scipy.stats import norm
norm.cdf(154, 161, 7)
norm.ppf(0.9, 161, 7)   # percentage

# Generate 10 random heights
norm.rvs(161, 7, size=10)

array([159.25312381, 165.99642257, 159.99545698, 162.19182857,
       161.23004516, 159.00432309, 159.88180417, 162.72795032,
       157.17884244, 160.39917631])

In [14]:
# rolling a dice
import pandas as pd
import numpy as np
die = pd.Series([1, 2, 3, 4, 5, 6])
# Roll 5 times
samp_5 = die.sample(5, replace=True)
print(samp_5)
np.mean(samp_5)

sample_mean = []
sample_sds = []
for i in range(10):
    samp_5 = die.sample(5, replace=True)
    sample_mean.append(np.mean(samp_5))
    # sample_mean.append(np.mean(die.sample(5, replace=True)))
    sample_sds.append(np.std(die.sample(5, replace=True)))

# estimate expected value of die
np.mean(sample_mean)

2    3
3    4
5    6
2    3
0    1
dtype: int64


In [18]:
# poisson distribution
from scipy.stats import poisson
poisson.pmf(5, 8)   # P(# adoptions in a week = 5)
poisson.cdf(5, 8)   # P(# adoptions in a week <=5)
1 - poisson.cdf(5, 8)   # P(week > 5)

poisson.rvs(8, size=10) # simulate 10 different weeks


array([ 7,  4,  5, 11,  3, 11,  7,  8,  9,  8])

In [ ]:
# exponential distribution
# probability of time between poisson events
# eg. probability of >1 day between adoptions
