In [7]:
matrix_1 = [[1,1,1], [1,1,1], [1,1,1]]
matrix_2 = [[1,1,1], [1,1,1], [1,1,1]]
result = [[0,0,0], [0,0,0], [0,0,0]]

for i in range(len(matrix_1)):
    for j in range(len(matrix_2[0])):
        for k in range(len(matrix_2)):
            result[i][j] += matrix_1[i][k] * matrix_2[k][j]
for r in result:
    print(r)

[3, 3, 3]
[3, 3, 3]
[3, 3, 3]


In [23]:
def matrix_input(rows: int, cols: int):
    list_1 = [[[0]*cols]*rows]
    for i in range(rows):
        for j in range(cols):
            num = input()
            list_1[i][j] += num
    return list_1

matrix_1 = matrix_input(3, 2)
print(matrix_1)

IndexError: list index out of range

In [1]:
import numpy as np

def input_sqmatrix(size, *args):
    matrix1 = [[0] * size for _ in range(size)]
    for i in range(size):
        for j in range(size):
            matrix1[i][j] = args[i * size + j]
    return matrix1

print("First Matrix: ")
matrix1 = input_sqmatrix(3, 1, 1, 1, 1, 1, 1, 1, 1, 1)
for row in matrix1:
    print(row)

print("Second Matrix: ")
matrix2 = input_sqmatrix(3, 1, 1, 1, 1, 1, 1, 1, 1, 1)
for row in matrix2:
    print(row)

result = np.dot(np.array(matrix1), np.array(matrix2))
print("Resultant Matrix: ")
for res in result:
    print(res)

First Matrix: 
[1, 1, 1]
[1, 1, 1]
[1, 1, 1]
Second Matrix: 
[1, 1, 1]
[1, 1, 1]
[1, 1, 1]
Resultant Matrix: 
[3 3 3]
[3 3 3]
[3 3 3]
