In [1]:
# String 
x = "body mass index"
y = 'this works too'
type (y)

str

In [2]:
# Boolean
z = True
type(z)

bool

In [8]:
# Summation of two num.
2 + 3

5

In [7]:
# Summation of two strings
'ab' + 'cd'

'abcd'

In [9]:
monthly_savings = 10
num_months = 12
intro = "Hello! How are you?"

# Calculate year_savings using monthly_savings and num_months
year_savings = monthly_savings * num_months

# Print the type of year_savings
print(type(year_savings))

# Assign sum of intro and intro to doubleintro
double_intro = intro + intro

# Print out doubleintro
print(double_intro)

<class 'int'>
Hello! How are you?Hello! How are you?


In [15]:
# list
fan1 = [['ABC', 1,11],
        ['DEF', 2.22],
        ['GHI', 3.33]]
print(fan1)
type(fan1)

[['ABC', 1, 11], ['DEF', 2.22], ['GHI', 3.33]]


list

In [16]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway",hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


In [19]:
# Printing the strings from the index
fam = ['abc', 1.73, 'def', 1.68, 'ghi', 1.71, 'jkl', 1.89]
print(fam)
print(fam[6])
print(fam[-1])
print(fam[1] + fam[-1])
print(fam[3:5]) # end index element is not printed
print(fam[:4])  # starting index is 0
print(fam[3:]) # end index is the last index of the list

['abc', 1.73, 'def', 1.68, 'ghi', 1.71, 'jkl', 1.89]
jkl
1.89
3.62
[1.68, 'ghi']
['abc', 1.73, 'def', 1.68]
[1.68, 'ghi', 1.71, 'jkl', 1.89]


In [25]:
# Modifying the elements in list
fam = ['abc', 1.73, 'def', 1.68, 'ghi', 1.71, 'jkl', 1.89]
fam[-1] = 1.86
print(fam)

# Adding the element in list
fam_ext = fam + ["mno", 1.79]
print(fam_ext)

# Deleting the element from the list
del(fam[2])
print(fam)

# List are stored by using the references
x = ["a", "b", "c"]
y = x
y[1] = "z"
print(y)
print(x)

# For not affecting the x list
x = ["a", "b", "c"]
y = x[:] # y = list(x)
y[1] = "z"
print(y)
print(x)

['abc', 1.73, 'def', 1.68, 'ghi', 1.71, 'jkl', 1.86]
['abc', 1.73, 'def', 1.68, 'ghi', 1.71, 'jkl', 1.86, 'mno', 1.79]
['abc', 1.73, 1.68, 'ghi', 1.71, 'jkl', 1.86]
['a', 'z', 'c']
['a', 'z', 'c']
['a', 'z', 'c']
['a', 'b', 'c']


In [4]:
# Functions
fam = [1.73, 1.68, 1.71, 1.89]
print(max(fam))
print(round(1.68, 1))   # round to the 1 decimal place
print(round(1.68)) # round to the closet integer

1.89
1.7
2


In [12]:
# Functions
fam = ['liz', 1.73, 'emma', 1.68, 'mom', 1.73, 'dad', 1.89]
print(fam.index("dad"))
print(fam.count(1.73))

sister = 'liz'
print(sister.capitalize())
print(sister.replace('z', 'sa'))
fam.append('me')
print(fam)

6
2
Liz
lisa
['liz', 1.73, 'emma', 1.68, 'mom', 1.73, 'dad', 1.89, 'me']


In [9]:
# Importing the packages
import numpy as np
np.array([1, 2, 3])

from numpy import array # Another way 
array([1, 2, 3])

import numpy as np
fam = ['liza', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
fam_ext = fam + ['me', 1.79]
print(str(len(fam_ext)) + " elements in fan_ext")
np_fam = np.array(fam_ext)  # Clearly using NumPy
print(np_fam)

10 elements in fan_ext
['liza' '1.73' 'emma' '1.68' 'mom' '1.71' 'dad' '1.89' 'me' '1.79']


In [14]:
# NumPy
import numpy as np
height = ([1.73, 1.68, 1.71, 1.89, 1.79])
np_height = np.array(height)
print(np_height)

weight = ([65.4, 59.2, 63.6, 88.4, 68.7])
np_weigth = np.array(weight)
print(np_weigth)

bmi = np_weigth / np_height
print(bmi)
print(bmi[2])
print(bmi > 40)
print(bmi[bmi > 40])

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]
[37.80346821 35.23809524 37.19298246 46.77248677 38.37988827]
37.19298245614035
[False False False  True False]
[46.77248677]


In [26]:
# 2D NumPy Arrays
import numpy as np
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
[65.4, 59.2, 63.6, 88.4, 68.7]])
print(np_2d)
print(np_2d.shape)  # (2, 5) 2 rows and 5 columns
print(np_2d[1])
print(np_2d[0][1])  # (np_2d[0, 1])
print(np_2d[:, 1:3])
print(np_2d[1, :])

print(np.mean(np_2d[:, 0]))  # Mean
print(np.median(np_2d[:, 0]))    #Median 
print(np.corrcoef(np_2d[:, 0], np_2d[:, 1]))   # Correlation
print(np.std(np_2d[:, 0]))   # Standard deviation

height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
print(height)

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]
(2, 5)
[65.4 59.2 63.6 88.4 68.7]
1.68
[[ 1.68  1.71]
 [59.2  63.6 ]]
[65.4 59.2 63.6 88.4 68.7]
33.565000000000005
33.565000000000005
[[1. 1.]
 [1. 1.]]
31.835000000000004
[2.29 1.68 2.08 ... 1.97 1.83 1.59]
